# Fraud / Anomaly Detection
## Notebook 02 — Data Cleaning

### Objective

Clean and validate the transaction dataset while preserving potentially meaningful anomalous observations.

### Important Principle

An unusual transaction is not automatically a bad data point.

Because this is an anomaly detection project, potential outliers must be preserved for later analysis.

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/Users/lingareddydhanushkumar/Desktop/Codex/ML/02_Fraud_Anomaly_Detection/data/raw/creditcard.csv")

In [5]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [7]:
clean_df = df.copy()

In [9]:
clean_df.shape

(284807, 31)

In [11]:
clean_df.columns.tolist()

['Time',
 'V1',
 'V2',
 'V3',
 'V4',
 'V5',
 'V6',
 'V7',
 'V8',
 'V9',
 'V10',
 'V11',
 'V12',
 'V13',
 'V14',
 'V15',
 'V16',
 'V17',
 'V18',
 'V19',
 'V20',
 'V21',
 'V22',
 'V23',
 'V24',
 'V25',
 'V26',
 'V27',
 'V28',
 'Amount',
 'Class']

In [13]:
clean_df.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object

In [15]:
missing = clean_df.isnull().sum()

missing

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [17]:
missing = clean_df.isnull().sum()

missing

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [19]:
duplicates = clean_df[clean_df.duplicated(keep=False)]

duplicates.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
32,26.0,-0.529912,0.873892,1.347247,0.145457,0.414209,0.100223,0.711206,0.176066,-0.286717,...,0.046949,0.208105,-0.185548,0.001031,0.098816,-0.552904,-0.073288,0.023307,6.14,0
33,26.0,-0.529912,0.873892,1.347247,0.145457,0.414209,0.100223,0.711206,0.176066,-0.286717,...,0.046949,0.208105,-0.185548,0.001031,0.098816,-0.552904,-0.073288,0.023307,6.14,0
34,26.0,-0.535388,0.865268,1.351076,0.147575,0.433680,0.086983,0.693039,0.179742,-0.285642,...,0.049526,0.206537,-0.187108,0.000753,0.098117,-0.553471,-0.078306,0.025427,1.77,0
35,26.0,-0.535388,0.865268,1.351076,0.147575,0.433680,0.086983,0.693039,0.179742,-0.285642,...,0.049526,0.206537,-0.187108,0.000753,0.098117,-0.553471,-0.078306,0.025427,1.77,0
112,74.0,1.038370,0.127486,0.184456,1.109950,0.441699,0.945283,-0.036715,0.350995,0.118950,...,0.102520,0.605089,0.023092,-0.626463,0.479120,-0.166937,0.081247,0.001192,1.18,0

In [21]:
duplicates.shape

(1854, 31)

In [23]:
clean_df = clean_df.drop_duplicates()

In [25]:
clean_df.shape

(283726, 31)

In [27]:
clean_df.duplicated().sum()

0

In [29]:
np.isinf(clean_df.select_dtypes(include=np.number)).sum().sum()

0

In [33]:
clean_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Time,283726.0,94811.077600,47481.047891,0.000000,54204.750000,84692.500000,139298.000000,172792.000000
V1,283726.0,0.005917,1.948026,-56.407510,-0.915951,0.020384,1.316068,2.454930
V2,283726.0,-0.004135,1.646703,-72.715728,-0.600321,0.063949,0.800283,22.057729
V3,283726.0,0.001613,1.508682,-48.325589,-0.889682,0.179963,1.026960,9.382558
V4,283726.0,-0.002966,1.414184,-5.683171,-0.850134,-0.022248,0.739647,16.875344
V5,283726.0,0.001828,1.377008,-113.743307,-0.689830,-0.053468,0.612218,34.801666
V6,283726.0,-0.001139,1.331931,-26.160506,-0.769031,-0.275168,0.396792,73.301626
V7,283726.0,0.001801,1.227664,-43.557242,-0.552509,0.040859,0.570474,120.589494
V8,283726.0,-0.000854,1.179054,-73.216718,-0.208828,0.021898,0.325704,20.007208
V9,283726.0,-0.001596,1.095492,-13.434066,-0.644221,-0.052596,0.595977,15.594995
V10,283726.0,-0.001441,1.076407,-24.588262,-0.535578,-0.093237,0.453619,23.745136
V11,283726.0,0.000202,1.018720,-4.797473,-0.761649,-0.032306,0.739579,12.018913
V12,283726.0,-0.000715,0.994674,-18.683715,-0.406198,0.139072,0.616976,7.848392
V13,283726.0,0.000603,0.995430,-5.791881,-0.647862,-0.012927,0.663178,7.126883
V14,283726.0,0.000252,0.952215,-19.214325,-0.425732,0.050209,0.492336,10.526766
V15,283726.0,0.001043,0.914894,-4.498945,-0.581452,0.049299,0.650104,8.877742
V16,283726.0,0.001162,0.873696,-14.129855,-0.466860,0.067119,0.523512,17.315112
V17,283726.0,0.000170,0.842507,-25.162799,-0.483928,-0.065867,0.398972,9.253526
V18,283726.0,0.001515,0.837378,-9.498746,-0.498014,-0.002142,0.501956,5.041069
V19,283726.0,-0.000264,0.813379,-7.213527,-0.456289,0.003367,0.458508,5.591971
V20,283726.0,0.000187,0.769984,-54.497720,-0.211469,-0.062353,0.133207,39.420904
V21,283726.0,-0.000371,0.723909,-34.830382,-0.228305,-0.029441,0.186194,27.202839
V22,283726.0,-0.000015,0.724550,-10.933144,-0.542700,0.006675,0.528245,10.503090
V23,283726.0,0.000198,0.623702,-44.807735,-0.161703,-0.011159,0.147748,22.528412
V24,283726.0,0.000214,0.605627,-2.836627,-0.354453,0.041016,0.439738,4.584549
V25,283726.0,-0.000232,0.521220,-10.295397,-0.317485,0.016278,0.350667,7.519589
V26,283726.0,0.000149,0.482053,-2.604551,-0.326763,-0.052172,0.240261,3.517346
V27,283726.0,0.001763,0.395744,-22.565679,-0.070641,0.001479,0.091208,31.612198
V28,283726.0,0.000547,0.328027,-15.430084,-0.052818,0.011288,0.078276,33.847808
Amount,283726.0,88.472687,250.399437,0.000000,5.600000,22.000000,77.510000,25691.160000
Class,283726.0,0.001667,0.040796,0.000000,0.000000,0.000000,0.000000,1.000000

In [35]:
clean_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Time,283726.0,94811.077600,47481.047891,0.000000,54204.750000,84692.500000,139298.000000,172792.000000
V1,283726.0,0.005917,1.948026,-56.407510,-0.915951,0.020384,1.316068,2.454930
V2,283726.0,-0.004135,1.646703,-72.715728,-0.600321,0.063949,0.800283,22.057729
V3,283726.0,0.001613,1.508682,-48.325589,-0.889682,0.179963,1.026960,9.382558
V4,283726.0,-0.002966,1.414184,-5.683171,-0.850134,-0.022248,0.739647,16.875344
V5,283726.0,0.001828,1.377008,-113.743307,-0.689830,-0.053468,0.612218,34.801666
V6,283726.0,-0.001139,1.331931,-26.160506,-0.769031,-0.275168,0.396792,73.301626
V7,283726.0,0.001801,1.227664,-43.557242,-0.552509,0.040859,0.570474,120.589494
V8,283726.0,-0.000854,1.179054,-73.216718,-0.208828,0.021898,0.325704,20.007208
V9,283726.0,-0.001596,1.095492,-13.434066,-0.644221,-0.052596,0.595977,15.594995
V10,283726.0,-0.001441,1.076407,-24.588262,-0.535578,-0.093237,0.453619,23.745136
V11,283726.0,0.000202,1.018720,-4.797473,-0.761649,-0.032306,0.739579,12.018913
V12,283726.0,-0.000715,0.994674,-18.683715,-0.406198,0.139072,0.616976,7.848392
V13,283726.0,0.000603,0.995430,-5.791881,-0.647862,-0.012927,0.663178,7.126883
V14,283726.0,0.000252,0.952215,-19.214325,-0.425732,0.050209,0.492336,10.526766
V15,283726.0,0.001043,0.914894,-4.498945,-0.581452,0.049299,0.650104,8.877742
V16,283726.0,0.001162,0.873696,-14.129855,-0.466860,0.067119,0.523512,17.315112
V17,283726.0,0.000170,0.842507,-25.162799,-0.483928,-0.065867,0.398972,9.253526
V18,283726.0,0.001515,0.837378,-9.498746,-0.498014,-0.002142,0.501956,5.041069
V19,283726.0,-0.000264,0.813379,-7.213527,-0.456289,0.003367,0.458508,5.591971
V20,283726.0,0.000187,0.769984,-54.497720,-0.211469,-0.062353,0.133207,39.420904
V21,283726.0,-0.000371,0.723909,-34.830382,-0.228305,-0.029441,0.186194,27.202839
V22,283726.0,-0.000015,0.724550,-10.933144,-0.542700,0.006675,0.528245,10.503090
V23,283726.0,0.000198,0.623702,-44.807735,-0.161703,-0.011159,0.147748,22.528412
V24,283726.0,0.000214,0.605627,-2.836627,-0.354453,0.041016,0.439738,4.584549
V25,283726.0,-0.000232,0.521220,-10.295397,-0.317485,0.016278,0.350667,7.519589
V26,283726.0,0.000149,0.482053,-2.604551,-0.326763,-0.052172,0.240261,3.517346
V27,283726.0,0.001763,0.395744,-22.565679,-0.070641,0.001479,0.091208,31.612198
V28,283726.0,0.000547,0.328027,-15.430084,-0.052818,0.011288,0.078276,33.847808
Amount,283726.0,88.472687,250.399437,0.000000,5.600000,22.000000,77.510000,25691.160000
Class,283726.0,0.001667,0.040796,0.000000,0.000000,0.000000,0.000000,1.000000

In [37]:

set(clean_df["Class"].unique()) - {0, 1}

set()

In [39]:
clean_df["Time"].min()

0.0

In [41]:
(clean_df["Amount"] < 0).sum()

0

In [43]:
print("Rows:", clean_df.shape[0])
print("Columns:", clean_df.shape[1])
print("Missing values:", clean_df.isnull().sum().sum())
print("Duplicate rows:", clean_df.duplicated().sum())
print(
    "Infinite values:",
    np.isinf(clean_df.select_dtypes(include=np.number)).sum().sum()
)

Rows: 283726
Columns: 31
Missing values: 0
Duplicate rows: 0
Infinite values: 0

In [53]:
import os

os.makedirs("data/processed", exist_ok=True)

clean_df.to_csv(
    "data/processed/creditcard_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [55]:
import os

os.makedirs("../data/processed", exist_ok=True)

output_path = "../data/processed/creditcard_cleaned.csv"

clean_df.to_csv(output_path, index=False)

print("Saved successfully!")
print("File:", output_path)
print("Exists:", os.path.exists(output_path))

Saved successfully!
File: ../data/processed/creditcard_cleaned.csv
Exists: True

In [57]:
import os

print(os.path.getsize("../data/processed/creditcard_cleaned.csv") / (1024 * 1024), "MB")

143.2880163192749 MB

In [59]:
clean_df.shape

(283726, 31)