In [1]:
# =====================================================
# Loan Approval Prediction Project
# Step 4 : Data Cleaning
# =====================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)

In [3]:
df = pd.read_csv("/Users/lingareddydhanushkumar/Desktop/Codex/ML/01_Loan_Approval_Prediction/data/LoanApprovalPrediction.csv")

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [5]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [7]:
loan_df = df.copy()

loan_df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [9]:
print("Rows :", loan_df.shape[0])
print("Columns :", loan_df.shape[1])

Rows : 598
Columns : 13

In [11]:
loan_df.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           12
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           21
Loan_Amount_Term     14
Credit_History       49
Property_Area         0
Loan_Status           0
dtype: int64

In [13]:
missing = pd.DataFrame({
    "Missing Values": loan_df.isnull().sum(),
    "Percentage": round(loan_df.isnull().mean() * 100, 2)
})

missing[missing["Missing Values"] > 0]

                  Missing Values  Percentage
Dependents                    12        2.01
LoanAmount                    21        3.51
Loan_Amount_Term              14        2.34
Credit_History                49        8.19

In [15]:
loan_df.drop("Loan_ID", axis=1, inplace=True)

loan_df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [17]:
print("Duplicate Rows :", loan_df.duplicated().sum())
loan_df.drop_duplicates(inplace=True)

Duplicate Rows : 0

In [19]:
num_cols = loan_df.select_dtypes(include=["int64", "float64"]).columns

print(num_cols)

Index(['Dependents', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History'],
      dtype='object')

In [21]:
cat_cols = loan_df.select_dtypes(include="object").columns

print(cat_cols)

Index(['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area',
       'Loan_Status'],
      dtype='object')

In [23]:
loan_df["Dependents"].fillna(
    loan_df["Dependents"].mode()[0],
    inplace=True
)

In [25]:
loan_df["LoanAmount"].fillna(
    loan_df["LoanAmount"].median(),
    inplace=True
)

In [27]:
loan_df["Loan_Amount_Term"].fillna(
    loan_df["Loan_Amount_Term"].mode()[0],
    inplace=True
)

In [29]:
loan_df["Credit_History"].fillna(
    loan_df["Credit_History"].mode()[0],
    inplace=True
)

In [31]:
loan_df.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [55]:
import os

os.makedirs(
    "/Users/lingareddydhanushkumar/Desktop/Codex/ML/01_Loan_Approval_Prediction/data/processed",
    exist_ok=True
)

In [57]:
loan_df.to_csv(
    "/Users/lingareddydhanushkumar/Desktop/Codex/ML/01_Loan_Approval_Prediction/data/processed/loan_clean.csv",
    index=False
)

In [59]:
import os

path = "/Users/lingareddydhanushkumar/Desktop/Codex/ML/01_Loan_Approval_Prediction/data/processed/loan_clean.csv"

print(os.path.exists(path))

True